### PR TITLE
Fix latest and experimental URL resolution

### LINKED ISSUE #287: Plugin json containing custom URLs does not use repository mirrors
If a plugin resolves using latest or experimental versions and the plugin metadata json defines a url it ignores any repository mirrors and uses that url directly. This causes problems when proxies/policies restrict hitting the internet directly instead requiring use of a repository mirror.

While mirroring arbitrary urls is not really feasible it should at least detect if the URL is repo.jenkins-ci.org or updates.jenkins.io and use the corresponding mirror if configured.

Code is [here](https://github.com/jenkinsci/plugin-installation-manager-tool/blob/master/plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java#L1038) and [here](https://github.com/jenkinsci/plugin-installation-manager-tool/blob/master/plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java#L1046)

**Expected:**
URLs in the plugins info json are translated to use the repository mirrors when applicable

**Actual:**
URLs in the plugins info json are hit directly

**Example:** 

jackson2-api

> java.exe -jar jenkins-plugin-manager-2.5.0.jar --jenkins-version 2.263.2 --jenkins-update-center <mirror1>/stable/update-center.json --jenkins-experimental-update-center <mirror1>/experimental/update-center.actual.json --jenkins-plugin-info <mirror1>/current/plugin-versions.json --jenkins-incrementals-repo-mirror <mirror2> --verbose --plugins jackson2-api:latest -d .
> 
> jackson2-api depends on:
> snakeyaml-api 1.27.0
> Setting checksum for: snakeyaml-api to ElUO5EweRQAHyVnzPS/6cW+4xq8hfZhIgPrEjd+FQuA=
> 
> snakeyaml-api has no dependencies
> Setting checksum for: jackson2-api to 2nJnob6/CTeTLvhkPlhf/dubBoAkuJwHSfwf7G/qgfs=
> Setting checksum for: jackson2-api to 2nJnob6/CTeTLvhkPlhf/dubBoAkuJwHSfwf7G/qgfs=
> Will install new plugin jackson2-api 2.12.1
> Will install new plugin snakeyaml-api 1.27.0
> Will use url: https://updates.jenkins.io/download/plugins/snakeyaml-api/1.27.0/snakeyaml-api.hpi to download snakeyaml-api plugin
> Will use url: https://updates.jenkins.io/download/plugins/jackson2-api/2.12.1/jackson2-api.hpi to download jackson2-api plugin
> Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/snakeyaml-api/1.27.0/snakeyaml-api.hpi, or download plugin snakeyaml-api to file
> Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/jackson2-api/2.12.1/jackson2-api.hpi, or download plugin jackson2-api to file
> Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/jackson2-api/2.12.1/jackson2-api.hpi, or download plugin jackson2-api to file
> Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/snakeyaml-api/1.27.0/snakeyaml-api.hpi, or download plugin snakeyaml-api to file
> Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/jackson2-api/2.12.1/jackson2-api.hpi, or download plugin jackson2-api to file
> Downloaded file is not a valid ZIP
> java.io.FileNotFoundException: C:\Users\mrichar2\AppData\Local\Temp\plugin-installation-manager-downloads7889007758612096344\jackson2-api.jpi (The system cannot find the file specified)

### PR DESCRIPTION
**Pull request by cronik**
When `--latest-specified` or `--latest` is enabled plugins will be resolved to the
latest plugin version but also be marked as `latest = true`. When this happens
the download url should use the configured download url
(i.e. `JENKINS_UC_DOWNLOAD_URL`) or jenkins update center
(i.e. `JENKINS_UC`).

Similar for plugins that specify the "experimental" version should use the
jenkins experimental update center (i.e. `JENKINS_UC_EXPERIMENTAL `).
Unlike "latest" these don't appear to be resolved to specific versions prior
to resolving the download url.

Fixes #287 

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

File: plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java [hunk 1]
```diff
@@ -1169,11 +1175,29 @@ public void getDownloadPluginUrlCustomUcUrls() throws IOException {
         assertThat(pluginManager.getPluginDownloadUrl(plugin))
                 .isEqualTo("https://private-mirror.com/jenkins-updated-center/dynamic-stable-2.319.1/latest/pluginName.hpi");
 
+        // lastest version with resolved version
```
Comment (timja) [inline plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java:1178]:
```suggestion
        // latest version with resolved version
```

**Review by timja — APPROVED** [review]
Thanks!
