### PR TITLE
Optional plugins missing from update center should not fail installation

### LINKED ISSUE #294: Optional dependencies should not fail an installation when unfindable
Since `2.6.0`, I am unable to download a plugin installation with this single plugin requested: `email-ext`

```bash
❯ java -jar jenkins-plugin-manager-2.6.0.jar --plugins email-ext --list --no-download --plugin-download-directory "$(mktemp -d)"
Unable to open /usr/share/jenkins/jenkins.war
Unable to get Jenkins version from the WAR file /usr/share/jenkins/jenkins.war
War not found, installing all plugins: /usr/share/jenkins/jenkins.war
Unable to find plugin analysis-core in update center https://updates.jenkins.io/update-center.json
```

While it works properly with `2.5.0`.

```bash
❯ java -jar jenkins-plugin-manager-2.5.0.jar --plugins email-ext --no-download --list --plugin-download-directory "$(mktemp -d)"
Unable to open /usr/share/jenkins/jenkins.war
Unable to get Jenkins version from the WAR file /usr/share/jenkins/jenkins.war
War not found, installing all plugins: /usr/share/jenkins/jenkins.war

Installed plugins:

Bundled plugins:

All requested plugins:
bootstrap4-api 4.6.0-2
checks-api 1.5.0
display-url-api 2.3.4
echarts-api 4.9.0-4
email-ext 2.81
font-awesome-api 5.15.2-2
jackson2-api 2.12.1
jquery3-api 3.5.1-3
junit 1.48
mailer 1.32.1
matrix-project 1.18
plugin-util-api 2.0.0
popper-api 1.16.1-2
scm-api 2.6.4
script-security 1.76
snakeyaml-api 1.27.0
structs 1.22
token-macro 2.15
workflow-api 2.41
workflow-job 2.40
workflow-step-api 2.23
workflow-support 3.7

Plugins that will be downloaded:
bootstrap4-api 4.6.0-2
checks-api 1.5.0
display-url-api 2.3.4
echarts-api 4.9.0-4
email-ext 2.81
font-awesome-api 5.15.2-2
jackson2-api 2.12.1
jquery3-api 3.5.1-3
junit 1.48
mailer 1.32.1
matrix-project 1.18
plugin-util-api 2.0.0
popper-api 1.16.1-2
scm-api 2.6.4
script-security 1.76
snakeyaml-api 1.27.0
structs 1.22
token-macro 2.15
workflow-api 2.41
workflow-job 2.40
workflow-step-api 2.23
workflow-support 3.7

Resulting plugin list:
bootstrap4-api 4.6.0-2
checks-api 1.5.0
display-url-api 2.3.4
echarts-api 4.9.0-4
email-ext 2.81
font-awesome-api 5.15.2-2
jackson2-api 2.12.1
jquery3-api 3.5.1-3
junit 1.48
mailer 1.32.1
matrix-project 1.18
plugin-util-api 2.0.0
popper-api 1.16.1-2
scm-api 2.6.4
script-security 1.76
snakeyaml-api 1.27.0
structs 1.22
token-macro 2.15
workflow-api 2.41
workflow-job 2.40
workflow-step-api 2.23
workflow-support 3.7
Done
```

In the current `update-center.json`, `email-ext` declares its dependency to `analysis-core` like this:

```json
{
  "name": "analysis-core",
  "optional": true,
  "version": "1.54"
}
```

But `analysis-core` is not (anymore) in `update-center.json`. As the dependency is optional, I would expect the install to **not fail**.

My guess is that it is a regression from the [new handling of optional dependencies](https://github.com/jenkinsci/plugin-installation-manager-tool/pull/288).

### PR DESCRIPTION
**Pull request by yabberyabber**
When resolving plugin, we will eagerly check the update center
for plugin metadata, even when that plugin is optional. When the
plugin is missing from update center, we end up failing the
installation.

This does not make sense for optional plugins. These plugins are
likely never going to be installed, so it isn't a problem that
we are missing some metadata. Instead of failing the build, we
just print a warning.

If another plugin does depend on this missing plugin in a
non-optional way, we will fail the installation at that point.

Fixes #294

### CODE REVIEW

File: plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java [hunk 1]
```diff
@@ -912,16 +912,26 @@ public VersionNumber getLatestPluginVersion(String pluginName) {
...
+                    VersionNumber latestPluginVersion = getLatestPluginVersion(pluginName);
+                    dependentPlugin.setVersion(latestPluginVersion);
+                    dependentPlugin.setLatest(true);
+                }
+                dependentPlugins.add(dependentPlugin);
+            } catch (PluginNotFoundException e) {
+                if (!dependentPlugin.getOptional()) {
+                    throw e;
+                }
+                logWarning(String.format(
```
Comment (timja) [inline plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java:929]: I think this should be under `logVerbose` the user hasn't done anything wrong here, the plugin needs to be updated to remove the dependency

```suggestion
                logVerbose(String.format(
```

File: plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java [hunk 2]
```diff
@@ -1490,6 +1500,15 @@ public void logVerbose(String message) {
...
 
+    /**
+     * Outputs a message to standard error with a warning prefix.
+     *
+     * @param message informational string to output
+     */
+    public void logWarning(String message) {
+        System.err.println("WARN: " + message);
+    }
+
```
Comment (timja) [inline plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java:1511]: unneeded i think
```suggestion
```

**Comment by yabberyabber** [comment]
@timja I think this build error is a transient error. How can I retrigger?

**Comment by timja** [comment]
> @timja I think this build error is a transient error. How can I retrigger?

You can close your PR wait a few seconds and open it is the easiest if you don't have write access,

I've re-triggered for you though

**Comment by timja** [comment]
it failed a few times, i've deleted that agent =/
