### PR TITLE
Handle optional dependencies correctly - Fixes #286

### LINKED ISSUE #286: Version constraints for optional plugins must be honored
It appears that when a dependency is "optional", the version solver completely ignores its constraints. This issue outlines a particular example:
 - blueocean:1.24.3 depends on pipeline-model-extensions:1.6.0 here https://github.com/jenkinsci/blueocean-plugin/blob/blueocean-parent-1.24.3/pom.xml#L48
 - kubernetes:1.27.6 has an optional dependency on pipeline-model-extension:1.7.2 here https://github.com/jenkinsci/kubernetes-plugin/blob/kubernetes-1.27.6/pom.xml#L52

This causes the kubernetes plugin to fail to load at startup because a non-supported version of pipeline-model-extensions is installed.

# Steps to reproduce

```bash
 > java -jar jenkins-plugin-manager.jar--latest-specified --list --plugins kubernetes:1.27.6 blueocean:1.24.3
```

<details>
  <summary>Generated output</summary>

  ```

Installed plugins:

Bundled plugins:

All requested plugins:
ace-editor 1.0.1
apache-httpcomponents-client-4-api 4.5.10-2.0
authentication-tokens 1.4
blueocean 1.24.3
blueocean-autofavorite 1.2.3
blueocean-bitbucket-pipeline 1.24.3
blueocean-commons 1.24.3
blueocean-config 1.24.3
blueocean-core-js 1.24.3
blueocean-dashboard 1.24.3
blueocean-display-url 2.2.0
blueocean-events 1.24.3
blueocean-git-pipeline 1.24.3
blueocean-github-pipeline 1.24.3
blueocean-i18n 1.24.3
blueocean-jira 1.24.3
blueocean-jwt 1.24.3
blueocean-personalization 1.24.3
blueocean-pipeline-api-impl 1.24.3
blueocean-pipeline-editor 1.24.3
blueocean-pipeline-scm-api 1.24.3
blueocean-rest 1.24.3
blueocean-rest-impl 1.24.3
blueocean-web 1.24.3
bouncycastle-api 2.18
branch-api 2.0.20
cloudbees-bitbucket-branch-source 2.4.4
cloudbees-folder 6.14
credentials 2.3.13
credentials-binding 1.13
display-url-api 2.3.1
docker-commons 1.14
docker-workflow 1.23
durable-task 1.34
favorite 2.3.1
git 4.2.2
git-client 3.0.0
git-server 1.7
github 1.29.3
github-api 1.114.2
github-branch-source 2.6.0
handy-uri-templates-2-api 2.1.6-1.0
htmlpublisher 1.14
jackson2-api 2.11.2
jenkins-design-language 1.24.3
jira 3.0.14
jquery-detached 1.2.1
jsch 0.1.55.1
junit 1.29
kubernetes 1.27.6
kubernetes-client-api 4.11.1
kubernetes-credentials 0.7.0
mailer 1.32
matrix-project 1.7.1
mercurial 2.0
okhttp-api 3.12.12.2
pipeline-build-step 2.7
pipeline-graph-analysis 1.10
pipeline-input-step 2.8
pipeline-milestone-step 1.3.1
pipeline-model-api 1.6.0
pipeline-model-declarative-agent 1.1.1
pipeline-model-definition 1.6.0
pipeline-model-extensions 1.6.0
pipeline-stage-step 2.3
pipeline-stage-tags-metadata 1.6.0
plain-credentials 1.7
pubsub-light 1.13
scm-api 2.6.3
script-security 1.71
snakeyaml-api 1.26.4
sse-gateway 1.21
ssh-credentials 1.17.3
structs 1.20
token-macro 2.0
variant 1.3
workflow-api 2.40
workflow-basic-steps 2.18
workflow-cps 2.80
workflow-cps-global-lib 2.9
workflow-durable-task-step 2.31
workflow-job 2.33
workflow-multibranch 2.20
workflow-scm-step 2.9
workflow-step-api 2.22
workflow-support 3.3

Plugins that will be downloaded:
ace-editor 1.0.1
apache-httpcomponents-client-4-api 4.5.10-2.0
authentication-tokens 1.4
blueocean 1.24.3
blueocean-autofavorite 1.2.3
blueocean-bitbucket-pipeline 1.24.3
blueocean-commons 1.24.3
blueocean-config 1.24.3
blueocean-core-js 1.24.3
blueocean-dashboard 1.24.3
blueocean-display-url 2.2.0
blueocean-events 1.24.3
blueocean-git-pipeline 1.24.3
blueocean-github-pipeline 1.24.3
blueocean-i18n 1.24.3
blueocean-jira 1.24.3
blueocean-jwt 1.24.3
blueocean-personalization 1.24.3
blueocean-pipeline-api-impl 1.24.3
blueocean-pipeline-editor 1.24.3
blueocean-pipeline-scm-api 1.24.3
blueocean-rest 1.24.3
blueocean-rest-impl 1.24.3
blueocean-web 1.24.3
bouncycastle-api 2.18
branch-api 2.0.20
cloudbees-bitbucket-branch-source 2.4.4
cloudbees-folder 6.14
credentials 2.3.13
credentials-binding 1.13
display-url-api 2.3.1
docker-commons 1.14
docker-workflow 1.23
durable-task 1.34
favorite 2.3.1
git 4.2.2
git-client 3.0.0
git-server 1.7
github 1.29.3
github-api 1.114.2
github-branch-source 2.6.0
handy-uri-templates-2-api 2.1.6-1.0
htmlpublisher 1.14
jackson2-api 2.11.2
jenkins-design-language 1.24.3
jira 3.0.14
jquery-detached 1.2.1
jsch 0.1.55.1
junit 1.29
kubernetes 1.27.6
kubernetes-client-api 4.11.1
kubernetes-credentials 0.7.0
mailer 1.32
matrix-project 1.7.1
mercurial 2.0
okhttp-api 3.12.12.2
pipeline-build-step 2.7
pipeline-graph-analysis 1.10
pipeline-input-step 2.8
pipeline-milestone-step 1.3.1
pipeline-model-api 1.6.0
pipeline-model-declarative-agent 1.1.1
pipeline-model-definition 1.6.0
pipeline-model-extensions 1.6.0
pipeline-stage-step 2.3
pipeline-stage-tags-metadata 1.6.0
plain-credentials 1.7
pubsub-light 1.13
scm-api 2.6.3
script-security 1.71
snakeyaml-api 1.26.4
sse-gateway 1.21
ssh-credentials 1.17.3
structs 1.20
token-macro 2.0
variant 1.3
workflow-api 2.40
workflow-basic-steps 2.18
workflow-cps 2.80
workflow-cps-global-lib 2.9
workflow-durable-task-step 2.31
workflow-job 2.33
workflow-multibranch 2.20
workflow-scm-step 2.9
workflow-step-api 2.22
workflow-support 3.3

Resulting plugin list:
ace-editor 1.0.1
apache-httpcomponents-client-4-api 4.5.10-2.0
authentication-tokens 1.4
blueocean 1.24.3
blueocean-autofavorite 1.2.3
blueocean-bitbucket-pipeline 1.24.3
blueocean-commons 1.24.3
blueocean-config 1.24.3
blueocean-core-js 1.24.3
blueocean-dashboard 1.24.3
blueocean-display-url 2.2.0
blueocean-events 1.24.3
blueocean-git-pipeline 1.24.3
blueocean-github-pipeline 1.24.3
blueocean-i18n 1.24.3
blueocean-jira 1.24.3
blueocean-jwt 1.24.3
blueocean-personalization 1.24.3
blueocean-pipeline-api-impl 1.24.3
blueocean-pipeline-editor 1.24.3
blueocean-pipeline-scm-api 1.24.3
blueocean-rest 1.24.3
blueocean-rest-impl 1.24.3
blueocean-web 1.24.3
bouncycastle-api 2.18
branch-api 2.0.20
cloudbees-bitbucket-branch-source 2.4.4
cloudbees-folder 6.14
credentials 2.3.13
credentials-binding 1.13
display-url-api 2.3.1
docker-commons 1.14
docker-workflow 1.23
durable-task 1.34
favorite 2.3.1
git 4.2.2
git-client 3.0.0
git-server 1.7
github 1.29.3
github-api 1.114.2
github-branch-source 2.6.0
handy-uri-templates-2-api 2.1.6-1.0
htmlpublisher 1.14
jackson2-api 2.11.2
jenkins-design-language 1.24.3
jira 3.0.14
jquery-detached 1.2.1
jsch 0.1.55.1
junit 1.29
kubernetes 1.27.6
kubernetes-client-api 4.11.1
kubernetes-credentials 0.7.0
mailer 1.32
matrix-project 1.7.1
mercurial 2.0
okhttp-api 3.12.12.2
pipeline-build-step 2.7
pipeline-graph-analysis 1.10
pipeline-input-step 2.8
pipeline-milestone-step 1.3.1
pipeline-model-api 1.6.0
pipeline-model-declarative-agent 1.1.1
pipeline-model-definition 1.6.0
pipeline-model-extensions 1.6.0
pipeline-stage-step 2.3
pipeline-stage-tags-metadata 1.6.0
plain-credentials 1.7
pubsub-light 1.13
scm-api 2.6.3
script-security 1.71
snakeyaml-api 1.26.4
sse-gateway 1.21
ssh-credentials 1.17.3
structs 1.20
token-macro 2.0
variant 1.3
workflow-api 2.40
workflow-basic-steps 2.18
workflow-cps 2.80
workflow-cps-global-lib 2.9
workflow-durable-task-step 2.31
workflow-job 2.33
workflow-multibranch 2.20
workflow-scm-step 2.9
workflow-step-api 2.22
workflow-support 3.3
Done
  ```

</details>

Notice that the dependencies here contain pipeline-model-extensions:1.6.0.

At runtime, this causes the jenkins instance to fail to start with the following error:
```
SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Kubernetes plugin v1.27.6 (kubernetes)
java.io.IOException: Failed to load: Kubernetes plugin (1.27.6)
 - Update required: Pipeline: Declarative Extension Points API (1.6.0) to be updated to 1.7.2 or higher
```

# What I would have expected to see

Either an error claiming there is an "unsatisfiable constraint" (pipeline-model-extension cannot exist at both versions 1.7.2 and 1.6.0), or for the generated plugin set to include the later of the two versions (1.7.2).

### PR DESCRIPTION
**Pull request by yabberyabber**
The previous behavior around optional dependencies was incorrect in
some cases. If plugin A declares a required dependency on plugin C
at version N, and plugin B declares an optional dependency on plugin
C at version N+1, the resolver will completely ignore plugin B's
optional dependency and end up installing plugin C at version N. This
will break plugin B because plugin B is explicitly incompatible with
versions vefore its dependency.

To solve this, we keep optional plugins in the dependency graph until
the very end. If every dependency on a given plugin is optional, then
that plugin can be omitted from the resulting set. However, if any of
those plugins are non-optional, then that plugin must be included
in the result and the version of that plugin must be the highest
required version among all enumerated dependencies.

### CODE REVIEW

**Review by timja — COMMENTED** [review]
can you write some tests that cover this properly please

**Comment by yabberyabber** [comment]
Added some tests and fixed most of the unit tests.

One of the existing unit tests is not passing and I'm not sure why - I'll update this PR with a fix to that failing test once I figure out the issue.

**Comment by yabberyabber** [comment]
This approach has an issue - non-optional dependencies of optional dependencies are treated as non-optional dependencies even if those optional dependencies don't end up being mapped in. Will address on Monday and add additional test for this scenario

File: plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java [hunk 1]
```diff
@@ -930,7 +956,7 @@ public VersionNumber getLatestPluginVersion(String pluginName) {
 
     // TODO(oleg_nenashev): This method is private, because it is only a partial fix for https://github.com/jenkinsci/plugin-installation-manager-tool/issues/101
     // A full dependency graph resolution and removal of non-needed dependency trees is required
-    private Map<String, Plugin> resolveRecursiveDependencies(Plugin plugin, @CheckForNull Map<String, Plugin> topLevelDependencies) {
+    public Map<String, Plugin> resolveRecursiveDependencies(Plugin plugin, @CheckForNull Map<String, Plugin> topLevelDependencies) {
```
Comment (timja) [inline plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java:958]: there's a comment on line 957 that needs removing now

**Review by timja — APPROVED** [review]

File: plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java (hunk 1 above)
Comment (timja) [reply plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java:958]: (removed)
